Feature/dz3
polis-mail-ru/2018-db-kv pull request #22
Opened 2018-05-01 10:03 UTC by AlexAntufiev

2018-05-02 16:37 UTC, incubos requested changes
Нужно разобраться с тестами.

2018-05-02 16:37 UTC, incubos commented on src/test/java/ru/mail/polis/LoadTest.java
> -            Files.recursiveDelete(data);
Почему это удалено?

2018-05-02 16:37 UTC, incubos commented on src/test/java/ru/mail/polis/LoadTest.java
> -            Files.recursiveDelete(data);
Зачем это?
Тесты не предполагают, что их меняют в PR :) Можно только добавлять новые тесты.

2018-05-06 22:26 UTC, AlexAntufiev commented on src/test/java/ru/mail/polis/LoadTest.java
> -            Files.recursiveDelete(data);
Я это понимаю)
Там такая реализация хранилища, что нельзя удалить все файлы и папки из папки с хранилищем, поэтому пришлось убрать, теперь вернул, но добавил `dao.close()` в тестах

2018-05-07 10:50 UTC, incubos commented
В 10 с уложиться не удалось:
```
$ time ./gradlew clean test

BUILD SUCCESSFUL in 36s
4 actionable tasks: 4 executed

real	0m36.660s
user	0m1.314s
sys	0m0.182s
```

2018-05-07 18:48 UTC, AlexAntufiev commented
я не понимаю, как уложиться в 10 сек, можете подсказать?

2018-05-08 09:33 UTC, incubos commented
Попробуйте поотлаживать, что делает Exodus. Кроме того, можно попрофилировать, например, при помощи [async-profiler](https://github.com/jvm-profiling-tools/async-profiler).
Возможно, появится инсайт или идеи, что можно потюнить.
Пишите результаты в этот тикет, какими бы они ни были.

2018-05-10 08:52 UTC, incubos commented
В крайнем случае, попробуйте переключиться на [другой сторадж](https://github.com/lmdbjava/benchmarks).

2018-05-30 18:39 UTC, AlexAntufiev commented
К сожалению, времени не хватило, чтобы реализовать хранилище, которое пройдет тесты за 10 секунд.

2018-07-04 09:32 UTC, incubos commented
Жаль.

2018-07-04 09:32 UTC, closed without merging