Load test
polis-mail-ru/2018-db-kv pull request #42
Opened 2018-05-09 20:29 UTC by vana06

Улучшил время прохождения тестов, но все равно не дотягиваю до 10 секунд. Пробовал использовать другие хранилища, но результат еще хуже. Чтобы дальше улучшить производительность скорее всего нужно реализовывать свою версию LSM дерева.

2018-05-10 09:59 UTC, incubos requested changes
Ошибка сборки в CI: https://travis-ci.org/polis-mail-ru/2018-db-kv/builds/377008133

2018-05-10 10:02 UTC, incubos commented
У Вас в ноутбуке SSD или HDD?

2018-05-10 10:03 UTC, vana06 commented
У меня стоит SSD. И вот это меня тоже удивило, почему так медленно

2018-05-10 10:03 UTC, incubos commented
Разработать свой LSM мы уже не успеем, скорее всего. Закомитьте в этот же PR другие реализации (на других хранилищах), которые Вы тестировали.
Попробуйте использовать маленькие транзакции и посмотреть на опции MapDB.

2018-05-16 14:01 UTC, incubos commented
С замечаниями, но принято.

2018-05-16 14:01 UTC, closed without merging